# Generated by Django 3.0.7 on 2021-02-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_user_photo'),
        ('trips', '0004_user_photo'),
    ]

    operations = [
    ]
